### ISSUE TITLE
Unable to run navidrome on musl

### ISSUE THREAD

**Issue by jvoisin** [deluan/navidrome#142]
I'm trying to have navidrome running on [Alpine Linux]( https://www.alpinelinux.org/ ), with [musl]( https://musl.libc.org/ ) as libc, but it seems that there are some symbols missing:

```
jukebox:/opt/navidrome# ldd navidrome
	/lib64/ld-linux-x86-64.so.2 (0x7fe77517e000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fe77517e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe77517e000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe77517e000)
Error relocating navidrome: fcntl64: symbol not found
jukebox:/opt/navidrome# 
```

Would it be possible to either not require them, or to ship a completely static build?

**Comment by deluan** [comment]
It's probably a SQLite dependency. I'll take a look and let you know

**Comment by deluan** [comment]
The binaries available from the releases are built on an Ubuntu based system, with glibc. 

Check if this binary works:
[navidrome.alpine.zip](https://github.com/deluan/navidrome/files/4431856/navidrome.alpine.zip)

If it works, I'll add an Alpine binary to automated release pipeline

**Comment by jvoisin** [comment]
It's working :)

**Comment by deluan** [comment]
Just for the records: while I don't add this to the release pipeline, the easiest way to get the latest binary for alpine is using Docker. Just run this command:
```
$ docker run -it -v $PWD:/data deluan/navidrome:develop cp navidrome /data/navidrome.alpine
```
And it will copy the binary from the image to the local dir, with the name `navidrome.alpine`. If you need a specific version, just use it instead of `develop`. Ex: `deluan/navidrome:latest` for the latest stable released version
