### ISSUE TITLE
“Username”, “user name” or “user-name” in English translation?

### ISSUE THREAD

**Issue by ElleshaHackett** [deluan/navidrome#231]
I think "user name" should be "username". - https://english.stackexchange.com/questions/43436/username-user-name-or-user-name

![image](https://user-images.githubusercontent.com/5116641/80378216-9ee05880-889c-11ea-9aa4-03f4eb3dde1e.png)

**Comment by deluan** [comment]
That should be a matter of adding the proper translation in the `en.js`. It is like that because React Admin "guesses" proper names based on field names. In this case `userName` becomes "User name". If we add a translation, it overrides this behaviour.

(Maybe the field should be called `username` :) )
