### ISSUE TITLE
Add a 'shuffle all' button for songs in webUI

### ISSUE THREAD

**Issue by stncrn** [deluan/navidrome#256]
I often like to listen to my whole music library, in random order.

Doing so with the current song page is almost impossible. The bulk action is only applied to the selected elements of the current page of the song list. So you have to select all on the first page, add to queue, go to the second page, repeat...

I already tried to implement the feature. The steps were:
- Adding the button, as `action` in the list. This button uses the `exporter` feature of the list, to be able to access all records, and not only the displayed (`ids`) or selected (`selectedIds`) ones.
- Using the dataProvider to call the API to get the songs from the song ids. I had to do this by chunks to avoid a 'too many SQL variables error on the API'. I also inserted the shuffeling here.
- Adding 2 actions to the player:
  - `addTracks`, that mimics `addTrack`: I had to do this to limit the number of calls to the `dispatch` function
  - `clearQueue`: very basic, to clear the queue only once, before adding all the songs in it

The current commit is here: https://github.com/stncrn/navidrome/commit/0ea60b76e1a102fdfe4e54340668507fb773303d

However, it is not ready for a pull request:
- This was my very first experience with react, redux, react-admin. So I guess some things could have been done in a better way.
- The processing time is slow: the first 2000 songs are added almost instantly to the queue, but the following ones are added slower and slower. It's still acceptable with the 6k library I used, but it would be a big issue with bigger ones. I made a quick demo video of the current implementation in action: 
[https://vimeo.com/413592965](https://vimeo.com/413592965)

It would be very great to have this feature added in Navidrome, and I hope that this preliminary work will help.

**Comment by deluan** [comment]
Thanks for taking a stab at this. My concern with this approach is what you already observed: It does not scale. My library for example has ~40K songs, and we have some users with more than 170K songs!!!!

I would implement this in a way similar to what Jamstash and DSub do: Have an option to generate a random playlist, where you can limit the size (no more than 1000), and even add some filters. This could be a dialog box in the Songs view, or part of the upcoming Playlist management feature.

Regarding your implementation, it is really good, specially for a first timer. The only thing I would change (not considering the whole "not-scaleable" approach) is to move the shuffling to an action, so instead of dispatching `addTracks` we would dispatch `shuffleTracks`. This would be more consistent to how we shuffle albums, for example. But again, I don't think we can make it scalable so I would think about a different approach.

**Comment by deluan** [comment]
Hey @stncrn, what do you think about adding an option to the `song` endpoint that retrieves up to 1000 random songs, possibly with genre, year, artist, filters? Then instead of loading all songs and randomize it in the UI, you'd get the list already randomized from the server, with one call.  IMHO, 1000 random songs is enough for a listening session (+2 days of music!) 

Let me know your thoughts about this, it would be pretty straightforward to implement this endpoint

**Comment by deluan** [comment]
I already [implemented the option in the `song` endpoint](https://github.com/deluan/navidrome/commit/c585ca71317189d835f2f3652b8110d7ca1c07d1). Just specify `random` as the sort field. Ex:
```
    dataProvider
      .getList('song', {
        pagination: { page: 1, perPage: 1000 },
        sort: { field: 'random', order: 'ASC' },
        filter: { },
      })
```

Keep in mind that there is no default limit for the `perPage` parameter. I may impose a limit to this (and all other) endpoint, probably around 1000 items, as I said before.

Feel free to experiment with this.

**Comment by coronawalrus** [comment]
Sorry, hadn't have a lot a free time recently.

You're definitely right, 1000 songs are more than enough. I didn't know that dSub was only creating a partial playlist when using the random button.

Great to see that you advanced on adding a random selection method on the song provider! I definitely did not thought it would be as simple.

I'll try to use it this weekend, and make the "shuffle (almost-)all" button finally usable.

**Comment by stncrn** [comment]
Sorry, hadn't have a lot a free time recently.

You're definitely right, 1000 songs are more than enough. I didn't know that dSub was only creating a partial playlist when using the random button.

Great to see that you advanced on adding a random selection method on the song provider! I definitely did not thought it would be as simple.

I'll try to use it this weekend, and make the "shuffle (almost-)all" button finally usable.

**Comment by deluan** [comment]
Commit 0730c66 implements a basic "Shuffle All" button, similar to what @stncrn proposed above. It plays up to 200 songs in random order. 

This functionality may evolve in the future, with options like max num songs, filter by genres, artists...

**Comment by mmatasic** [comment]
Can something similar be added for the album view?
