### ISSUE TITLE
[Unknown Artist/Album] when brackets present in filepath

### ISSUE THREAD

**Issue by Serpentsounds** [deluan/navidrome#28]
A majority of the entries in the Albums and Songs view show up as [Unknown Artist] and [Unknown Album] for me. I think I've narrowed it down to the bracket characters [] being present in the filepath. I organize folders like "Artist/[Date] Album/#. Title.ext." The only items that show up correctly in these views seem to be the stragglers that I haven't yet cleaned up naming scheme on.

Interestingly, in most cases the top level of the Artists view is fine, even if every song by a particular artist has a bracket in the filepath (i.e. the album artists seem to be picked up from the tags). Same story as before if I click on an artist though.

![navidrome-error](https://user-images.githubusercontent.com/10228387/73053860-e4812580-3e56-11ea-91cf-4ba5f6b95424.png)

**Comment by deluan** [comment]
I don't think the brackets in the path is the problem here. As a test I created a file with this path structure and it worked fine. I think this issue is related to way your tags are stored in the media file.

To better understand the issue, can you please provide:
1) Details on how are you running it. Docker? If not, which OS
2) Which software you used to tag the files
3) Can you send me one of these songs (via Dropbox, or something similar)?

**Comment by Serpentsounds** [comment]
That could be the case, as if a file is following that scheme I've likely edited the metadata. Didn't even think of that.

1. Running via Docker. Only thing I changed from the example compose file are the volume paths.
2. foobar2000
3. https://nextcloud.soredemo.net/s/kJDGpEz6AcomFb5

**Comment by deluan** [comment]
Found the issue: foobar2000 was tagging the file with uppercase tags

Just pushed a fix, docker image is building right now. You may have to delete your navidrome.db data file, to force a full rescan.

Please let me know how it goes.

**Comment by Serpentsounds** [comment]
Thanks for the update. It seems to be working for MP3 files but not FLAC files.

**Comment by deluan** [comment]
Closed with https://github.com/deluan/navidrome/commit/461b7424e9bb83e93f377a7631c91896bc3002c2
