### ISSUE TITLE
GetTopSongs not working with play:sub

### ISSUE THREAD

**Issue by BobWs** [deluan/navidrome#432]
Hi,
Thanks for all your hard work and great product! 

I saw in the change log of v 0.29 that `GetTopSongs` is implemented that’s great, but it is not working with play:sub. When I try to use `TopSongs` Within play:sub I get a error message that only api version 1.13.0 and above is supported. Any chance you could update the api to version 1.13 or newer?

**Comment by deluan** [comment]
Hey @BobWs, `GetTopSongs` (together with other Last.FM services, see #18) is not really implemented. It only returns a valid _empty response_ for now. I added this "fake" endpoint because some players (AVSub, Music Stash) do not check the server version and calls endpoints that may are not implemented, causing them to fail. The "fake" endpoints are just workaround for this bad behaviour :)

Because of that, there is no point in changing the api version for now. Once I finish working on `GetTopSongs`, I'll update the version, for sure.

I'm closing this issue, as the implementation will be covered in #18.

**Comment by BobWs** [comment]
Okay that makes sense, thanks for explaining looking forward when it is finally implemented.
