### ISSUE TITLE
Web UI: update and raise the items per page

### ISSUE THREAD

**Issue by praise-you** [deluan/navidrome#512]
Hello,

At the moment the current "Items per page" menu offers either "15, 25, 50" or "18, 36, 72".

I find this too low and would like to see "100" and "200" added.

I'm no developer but I went through the source to find out which file to edit and make a pull request but well here I am raising an issue!

Thanks

**Comment by deluan** [comment]
I've tried it in the past (https://github.com/deluan/navidrome/issues/132#issuecomment-631220249), but due to the way React and React-Admin work, this would cause a considerable slow down of the UI, specially in the Albums view. 

Newer versions of React-Admin may be more flexible and may make it easier to implement the infinite scroll, which would be preferable instead of the current paginated style. 

I keep this open to re-assess if there's something that can be done in the meantime while we don't have infinite scroll, but I don't really want to spend too much time on this, as it would be a temporary solution

**Comment by praise-you** [comment]
I hadn't thought of infinite scrolling which afaik is often described as bad by UI experts.

Anyway, thanks deluan, you rock!
