### ISSUE TITLE
iOS: "[Object object]" shown on lock screen controls instead of Artist - Song Title

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#526]
On iOS Safari, when the WebUI is playing in the background (with the screen locked), the iOS lock screen controls show `[object Object]` instead of the expected "Artist - Song Title" text.

The [demo](https://lijinke666.github.io/react-music-player/) React player does show that, so it seems that navidrome isn't setting a metadata attribute somewhere?

**Comment by deluan** [comment]
The issue is that I'm setting the Player's `audioTitle` property as a `<Link/>` component, to allow it to be clickable and go to the album being played. This makes the property an object. 

It works well in Android and in the [Media Session](https://github.com/lijinke666/react-music-player#bulb-media-session), but seems like iOS does not like this :/

I'll try to come up with a solution for this

**Comment by certuna** [comment]
Is this an issue for the upstream React player or with iOS itself?

**Comment by deluan** [comment]
The upstream library expects this value to be a string, but I did some tests and using a React component works, even though it complaints in the JS console.... As I didn't see any side effects (besides the console errors), I started using it. But if iOS can't handle this, I'll probably open an issue with the React Player project. 

For now, I may check if it is running on mobile and set the value as string instead of a component

**Comment by deluan** [comment]
Latest version of React Player introduced a `renderAudioTitle` that enables setting the title as a React component! Latest [build from master](https://github.com/deluan/navidrome/suites/1332927850/artifacts/21399815) already uses it. 

Please let me know if this works for iOS and iPadOS.

**Comment by rwoodpecker** [comment]
@deluan Thanks for this - confirmed working on iOS.
