### ISSUE TITLE
[Web client] Add a mouse hover play button

### ISSUE THREAD

**Issue by praise-you** [deluan/navidrome#530]
Goals:

1. To play quickly an album
2. To improve the UI

Current situation:

- To play an album you either click on an album, load a new page and then press play OR
- you hover on the picture, select the menu and press play.

Problem:

- Loading a new page is unnecessary
- If you're not sure which album you want to listen to it helps to play numerous albums before finding the one you want.

Proposed solution:

- Add a mouse hover button to play an album from the album view. It should replace the current playlist if there's one.
- Make it so that only the button will play the album and let the user load the album details page if he click's elsewhere on the album cover.

Quick and dirty mock-up:
![bb](https://user-images.githubusercontent.com/67846246/94346745-00187d80-002f-11eb-9ca7-405131177b3b.jpg)

Thanks!

**Comment by deluan** [comment]
This is hard to do ATM, because the way the album grid is structured. The "tiles" are. already cluttered with lots of info, and the [GridListTile](https://material-ui.com/api/grid-list-tile/) used is not flexible enough to easily implement this.

As I've been saying in our Discord channel, I'm planning on rewriting the whole grid using a different approach, to allow things like your request and also #513 .

I'll create a new issue, consolidating all things will be tackled by this rewrite, and link to this and other issues. While I don't do this, I'll keep this open

**Comment by certuna** [comment]
If the album grid could show/act like it does on iTunes/Music for example, that would be great. Play button on hover, show the cover + album artist/album title in the grid, and expand/collapse to the more detail (album artist/album title/genre/year) + tracklist on click/tap.

On mobile/touchscreen a different layout might be needed though - it's hard to design a UI that works equally effective both on portrait orientation + touch and landscape orientation + mouse

**Comment by deluan** [comment]
This was implemented in #608:
<img width="224" alt="Screen Shot 2020-11-03 at 10 06 56 AM" src="https://user-images.githubusercontent.com/331353/98003103-54481780-1dbc-11eb-8166-5549ad4885dc.png">
