### ISSUE TITLE
DB Migration 

### ISSUE THREAD

**Issue by gedw99** [deluan/navidrome#653]
You might want to change to genji dB.

https://github.com/genjidb/genji

All golang with sql. Zero CGO. Easy to backup in streaming mode. Works with goose.
Can store files as if was a file system.
Advanced caching
Behind it is badgerdb.
Fast like crazy

Files are uploaded/ downloaded as chunks so for massive files it’s not going to balloon the memory either

**Comment by deluan** [comment]
Thanks for the suggestion, I'd love to have something in pure Go, but the options available do not provides all functionality I need. 

Originally Navidrome (at the time called GoSonic), was created using LedisDB, but it was not well-suited for its use case. Then I tried Storm (a precursor of Genji): https://github.com/deluan/navidrome/tree/334e8384ce68e43424fa193bc85100c0872c340c/persistence/db_storm
The issue with it was that BoltDB/BBolt is too slow for the scan (too many writes), and the scanner was awfully slow because of that. At that point I did some experimentation with Badger and TieDot, but they were also too slow/not suited for Navidrome. 

I also looked at Genji, but as it is a layer on top of BoltDB/Badger, it would be as slow, or worse, and the API didn't have the features I needed.

The only real solution I see in pure Go would be TiDB when they offered a embeddable DB. Now they don't offer it anymore, so I'm stuck with SQLite... :/

Anyway thanks for the suggestion
