### ISSUE TITLE
Single-artist albums split in two

### ISSUE THREAD

**Issue by Spireshield** [deluan/navidrome#709]
Hello! I've been using Navidrome for a couple months now, and it's worked great. Thank you :)

When uploading certain single-artist albums, Navidrome will split the album in two: one will use the proper artist metadata, while the second will list the artist as "Various Artists". The metadata on all the songs in the album is the same, with both Artist and Album Artist set identically.

I set the tags on my Linux desktop, using Clementine. Both Clementine and EasyTAG display identical values for the tags. I upload the files over FTP to my server. I use predominantly m4a's, although I haven't determined whether this is an m4a-exclusive problem. I'm currently using version 0.39.0 in Docker. Jellyfin, reading from the same directory/files, displays the albums correctly. I've already reset/reinstalled Navidrome, the issue is persistent across installations.

Setting the Artist and Album Artist tags to "Various Artists" 'resolves' the problem in Navidrome, i.e., the album is again merged but under the "Various Artists" artist. I've attached example images below, note that the album in question is using m4a's.

Any help is appreciated, thank you!

![image](https://user-images.githubusercontent.com/16454255/103448858-608e0b00-4c6d-11eb-82b7-2102188856bc.png)
![image](https://user-images.githubusercontent.com/16454255/103448860-77ccf880-4c6d-11eb-9762-a858e0f1684d.png)

**Comment by deluan** [comment]
Seems that some tracks (the ones under "Various Artists") may have their "Compilation" flag as true: https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

Can you please post here the results of `ffmpeg -i track.m4a` for two tracks, one from each group?

**Comment by Spireshield** [comment]
Yep, the compilation tag is set at different values. For Track 6, the compilation tag is "84", while for Track 8, the compilation tag is "0". The former is part of the "Various Artists" group, while the latter is part of the correct group.

The entire album was ripped from the same CD, at the same time; I'm unsure why this are set differently. I'll take a look at ffmpeg to see if I can use that to change the metadata, is there a better program you'd recommend to do so however?

If I may, would it be possible for you to switch the album grouping to be dependent on the Artist Album tag, instead of this compilation tag?

Thanks for the timely response :)

**Comment by deluan** [comment]
All these software should allow you to change the tags: https://www.navidrome.org/docs/faq/#how-can-i-edit-my-music-metadata-id3-tags-how-can-i-renamemove-my-files 

I recommend Picard if you only need to edit tags. I personally use beets on Linux (to organize/tag my library), XLD (for FLAC ripping) and iTunes (for eventual tag editing) on macOS. 

To quickly remove the Compilation flag from your files with ffmpeg, try this: https://www.reddit.com/r/linuxquestions/comments/5rytta/id3_tags_compilations/ddcb6cj?utm_source=share&utm_medium=web2x&context=3

I don't have plans to introduce a config to specifically change the compilation/album artist behaviour. Navidrome is 100% tag driven and this is the expected behaviour for the (de facto standard) "Compilation" tag. Fixing the tag in your files is the recommended way, as it will make your library more consistent.

I'm closing this now, but feel free to reopen (or open a new issue) if you find any related problems.
