### ISSUE TITLE
[Feature Request] Folder View

### ISSUE THREAD

**Issue by Typhonragewind** [deluan/navidrome#739]
Love this project, and having tested it locally it works wonders.

There is just one thing missing that prevents me from switching. My collection is very large (around 39k songs) and contains some obscure music that even doesn't exist in MusicBrainz database, so it makes it a pain/nearly impossible to organize with tags.

Which is why i sort it through a folder and subfolder system.

I know this issue has been raised before in a closed ticket and i know you have more interesting features to develop than a folder view, but if you ever get a chance to do it, it would be truly appreciated!

**Comment by deluan** [comment]
Thanks for trying Navidrome.

As I said before, "Browse by Folder" is not in the plans for Navidrome, mostly because it would require too many changes, and as you noted there are lots of features I'd like to implement before even thinking of such big refactor.

By the way, my library has 70K songs, 5.2K albums. I also have some obscure albums. When they are proper releases I just add them to MusicBrainz. If they are a personal compilation, a bootleg or something like that, I use iTunes or Picard to edit the tags and set the album to whatever I want it to be displayed.

Having said that, I plan to implement three features that will help in these cases: 
1) Infer tags from paths: You will be able to extract artist/album/title/... from the path (see https://github.com/deluan/navidrome/issues/560)
2) Support for the grouping tag, and introduce navigation by Grouping. This will allow you to group albums in groups like : 'Soundtracks' or 'Bootlegs'
3) Smart playlists will be able to use the path

I know it is not a "Folder view", but it is the closest I can get without a big refactor, which is undesirable at this point. 

I'm closing this as these features are already being tracked in other issues.
