### ISSUE TITLE
Enforced 'create admin' dialog after session timeout

### ISSUE THREAD

**Issue by KacperBak** [deluan/navidrome#741]
If you ran into a session timeout with browser A, Navidrome enforces the 'create admin' dialog. A simple login is not possible anymore using browser A. To mitigate this one can simply use a browser instance that has no data cached from Navidrome, e.g. Incognito mode, an other browser B, etc. 

My case is documented [here](https://www.reddit.com/r/navidrome/comments/l1fd53/create_a_new_admin_using_old_data_folder/).

**Comment by lunik1** [comment]
I have been running into this too using the official docker image. On many browsers, `Ctrl+F5` should clear the cache and allow you to log in.

**Comment by deluan** [comment]
This is a bug caused by the current serviceWorker implementation, as part of the PWA implementation. It has been reported here: https://github.com/deluan/navidrome/issues/613

The solution for now is clear the browser's cache or "force" refresh the page with `Ctrl+F5` (or `Command+R` on macOS) as suggested by @lunik1 .

I'll close this as this bug is already been tracked in the other issue. Thanks for the report
